MyBlog/MyBlog/urls.py
from django.conf.urls import url,include
import xadmin
from homepage.views import *
from blogs.models import *
from django.views.static import serve
from settings import MEDIA_ROOT
from blogs import urls as blog_urls

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),

    url(r'^$',IndexView.as_view(),name='index'),

    url(r"^media/(?P<path>.*)$", serve,{"document_root":MEDIA_ROOT}),

    url(r'^ueditor/', include('DjangoUeditor.urls')),

    url(r'^blog/',include(blog_urls,namespace="blog")),

]

MyBlog/apps/blogs/urls.py
from django.conf.urls import url, include
from blogs.models import *
from blogs.views import *

urlpatterns = [
    url(r'desc/(?P<blogId>\d+)', BlogDescView.as_view(), name="blogDesc"),
    url(r'desc/add_click', add_click, name='add_click'),
    url(r'archive', ArchiveView.as_view(), name='archive'),
    url(r'category/(?P<categoryId>\d+)', CategoryAndTagView.as_view(), name='category'),
]

MyBlog/apps/blogs/models.py
# _*_ coding:utf-8 _*_

from django.db import models
from datetime import datetime
from django.utils import timezone
from DjangoUeditor.models import UEditorField


# from django.utils.timezone import utc

# now = datetime.utcnow().replace(tzinfo=utc)


# Create your models here.

class Tags(models.Model):
    # blog = models.ManyToManyField(Blog, verbose_name='博客')
    name = models.CharField(default="", blank=True, max_length=50, verbose_name='标签')
    add_time = models.DateTimeField(default=timezone.now, verbose_name="添加时间")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Category(models.Model):
    # blog = models.ManyToManyField(Blog, verbose_name='博客')
    name = models.CharField(default="", blank=True, max_length=50, verbose_name='标签')
    add_time = models.DateTimeField(default=timezone.now, verbose_name="添加时间")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name='标题')
    body = UEditorField(verbose_name='内容', width=600, height=300, imagePath="uedirotImg", filePath="ueditorFile")
    tags = models.ManyToManyField(Tags, verbose_name='标签')
    category = models.ManyToManyField(Category, verbose_name='分类')
    type = models.CharField(choices=(('yc','原创'),('zz','转载')),max_length=4,default="yc")
    click = models.IntegerField(default=0, verbose_name="点击数")
    add_time = models.DateTimeField(default=timezone.now, verbose_name="添加时间")

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "博客"
        verbose_name_plural = verbose_name

MyBlog/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

MyBlog/templates/_base.html
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include '_head.html' %}
</head>
<body>
<div class="my-header white">
    <a class="logo" href="{% url 'index' %}">
            <i>Pfx</i>
            <i>Blog</i>
    </a>
    <div id="category">
        <ul>
            <li><a href="{% url 'index' %}">博客</a></li>
            <li><a href="{% url 'blog:archive' %}">归档</a></li>
            <li><a href="#">文章</a></li>
            <li><a href="#">文章</a></li>
        </ul>
    </div>
</div>
<div id="my-body">
    <div class="my-content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="my-left">
        {% include '_left.html' %}
    </div>

    <div class="my-right">
        {% include '_right.html' %}
    </div>
</div>


<script>
    $(function () {
        $(".logo i").hover(function () {
            $(".logo i").addClass("logohover")
        });
        $(".logo i").mouseout(function () {
            $(".logo i").removeClass("logohover")
        })
    })
</script>

{% block js %}

{% endblock %}
</body>
</html>

MyBlog/templates/_head.html
{% load staticfiles %}

<!-- css files -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/left.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/my-paginator.css' %}">


<!-- js files -->
<script src="{% static 'js/jquery-1.12.4.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/get_cookie.js' %}"></script>

MyBlog/templates/_left.html
{% load staticfiles %}
<div class="left-main">
    <div class="my-clock white block">
        <script charset="Shift_JIS"
                src="http://chabudai.sakura.ne.jp/blogparts/honehoneclock/honehone_clock_tr.js"></script>
    </div>
    <div class="my-image white block">
        <img style="width: 200px" alt="" src="{% static 'image/head.jpg' %}">
        <p class="my-name">Pfx</p>
        <div class="my-category">
            <a class="my-a" href="#">
                <span>{{ category_num }}</span>
                <span>分类</span>
            </a>
            <div class="my-hor-line"></div>
            <a class="my-a" href="#">
                <span>{{ blog_num }}</span>
                <span>博客</span>
            </a>
            <div class="my-hor-line"></div>
            <a class="my-a" href="#">
                <span>{{ tag_num }}</span>
                <span>标签</span>
            </a>
            <div>

            </div>
        </div>
    </div>
    <div>

    </div>
</div>

MyBlog/templates/_right.html
{% load staticfiles %}

<div class="right-main ">
    <div class="white block pb10">
        <p class="category-title">全部分类</p>
        {% for category in categorys %}
            <p class="category-list"><a href="{% url 'blog:category' category.id %}">{{ category.name }}</a>&nbsp;&nbsp;({{ category.blog_set.count }})</p>
        {% endfor %}
    </div>
    <div class="white block mt10 pb10">
        <p class="category-title">标签</p>
        <div class="tags">
            {% for tag in tags %}
                <span class="tag"><a href="#">{{ tag.name }}</a></span>
            {% endfor %}
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.tag').each(function(){

        })
    })
</script>

MyBlog/templates/archive.html
{% extends '_base.html' %}

{% block title %}归档{% endblock %}

{% block content %}

    <div class="white block">
        {% regroup blogs.object_list by add_time.year as year_post_group %}

        <ul>
            {% for year in year_post_group %}
                <li class="archive-year">{{ year.grouper }} 年
                    {% regroup year.list by add_time.month as month_post_group %}
                    <ul class="archive-month">
                        {% for month in month_post_group %}
                            <li>{{ month.grouper }} 月
                                <ul>
                                    {% for post in month.list %}
                                        <li class="archive-title"><a
                                                href="{% url 'blog:blogDesc' post.id %}">{{ post.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% load i18n %}
    <div class="paginate">
        {% if blogs.has_previous %}
            <a href="?{{ blogs.previous_page_number.querystring }}"
               class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
        {% else %}
            <span class="disabled">&lsaquo;&lsaquo; {% trans "previous" %}</span>
        {% endif %}
        {% for page in blogs.pages %}
            {% if page %}
                {% ifequal page blogs.number %}
                    <span class="current page">{{ page }}</span>
                {% else %}
                    <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                {% endifequal %}
            {% else %}...{% endif %}
        {% endfor %}
        {% if blogs.has_next %}
            <a href="?{{ blogs.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
        {% else %}
            <span class="disabled">{% trans "next" %} &rsaquo;&rsaquo;</span>
        {% endif %}
    </div>

    <script>
        $(function () {
{#            $('.archive-year').each(function () {#}
{#                $(this).click(function () {#}
{#                    console.log(this);#}
{#                    console.log("1");#}
{#                    $(this).children('.archive-month').toggle(1000)#}
{#                })#}
{#            });#}
{#            $('.archive-month').each(function(){#}
{#                $(this).click(function(){#}
{#                    $(this).children('.archive-title').toggle(1000)#}
{#                })#}
{#            })#}
        })

    </script>
{% endblock %}

MyBlog/templates/blog-desc.html
{% extends '_base.html' %}
{% block title %}
{{ blog.title }}
{% endblock %}

{% block content %}
    <div class="block white desc-div">
        <h1 class="my-title">{{ blog.title }}</h1>
        <p class="blog-type">原创</p>
        <i class="glyphicon glyphicon-time"></i><span class="blog-time">{{ blog.add_time|date:"Y-m-d" }}</span>
        <i class="glyphicon glyphicon-list-alt" style="margin-left: 10px;margin-right: 5px" title="分类"></i>
        {% for category in blog.category.all %}
            <span class="blog-span">{{ category.name }}</span>
        {% endfor %}
        <span style="margin-left: 5px">点击量:</span>
        <span>{{ blog.click }}</span>
        {% autoescape off %}
            <p class="desc-body">{{ blog.body }}</p>
        {% endautoescape %}
        <hr>
        <i class="glyphicon glyphicon-tags" style="margin-right: 5px" title="标签"></i>
        {% for tags in blog.tags.all %}
            <span class="blog-span">{{ tags.name }}</span>
        {% endfor %}
        <hr>
        <p class="blog-comments">*本站文章除注明转载/出处外，均为本站原创或翻译，转载前请务必署名,转载请标明出处</p>
    </div>

{% endblock %}

MyBlog/templates/category.html
{% extends '_base.html' %}

{% block title %}{% if type == 1 %}分类：{% else %}标签：{% endif %}{{ categoryed.name }}{% endblock %}

{% block content %}
    <div class="block white">
        <p class="category-title category-h3">{% if type == 1 %}分类：{% else %}标签：{% endif %}{{ categoryed.name }}</p>
        {% for blog in bloged %}
            <i class="glyphicon glyphicon-file" style="margin-left: 50px"></i>
            <div class="category-div">
                <p>{{ blog.title }}</p>
            </div>
            <br>
        {% endfor %}
    </div>
{% endblock %}

MyBlog/templates/center-blog.html
{% extends '_base.html' %}
{% load staticfiles %}
{% block title %}首页{% endblock %}
{% block content %}

    <div class="my-center">
        {% for blog in blogs.object_list %}
            <div class="my-blog block white">
                <h3 class="blog-title" title="{{ blog.title }}"><a
                        href="{% url 'blog:blogDesc' blog.id %}">{{ blog.title }}</a></h3>
                <input id="hide-id" type="hidden" value="{{ blog.id }}">
                <p class="blog-type">原创</p>
                <i class="glyphicon glyphicon-time"></i><span class="blog-time">{{ blog.add_time|date:"Y-m-d" }}</span>
                <i class="glyphicon glyphicon-list-alt" style="margin-left: 10px;margin-right: 5px" title="分类"></i>
                {% for category in blog.category.all %}
                    <span class="blog-span">{{ category.name }}</span>
                {% endfor %}
                {# 将html语言转译成正常文本#}
                {#                {% autoescape off %}#}
                <p>{{ blog.body|slice:"0:200"|striptags }}{% if blog.body.length > 200 %}...{% endif %}</p>
                {#                {% endautoescape %}#}
                <hr>
                <i class="glyphicon glyphicon-tags" style="margin-right: 5px" title="标签"></i>
                {% for tags in blog.tags.all %}
                    <span class="blog-span">{{ tags.name }}</span>
                {% endfor %}
            </div>
        {% endfor %}

        <div class="pagination my-pagination">
            {% if blogs.has_previous %}
                <a href="?{{ blogs.previous_page_number.querystring }}"
                   class="prev page-border">&lsaquo;&lsaquo; </a>
            {% else %}
                <span class="disabled prev page-border">&lsaquo;&lsaquo; </span>
            {% endif %}
            {% for page in blogs.pages %}
                {% if page %}
                    {% ifequal page blogs.number %}
                        <span class="current page-border">{{ page }}</span>
                    {% else %}
                        <a href="?{{ page.querystring }}" class="page page-border">{{ page }}</a>
                    {% endifequal %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
            {% if blogs.has_next %}
                <a href="?{{ blogs.next_page_number.querystring }}" class="next page-border"> &rsaquo;&rsaquo;</a>
            {% else %}
                <span class="disabled next page-border">&rsaquo;&rsaquo;</span>
            {% endif %}
        </div>
    </div>

    {% block js %}
        <script>
            $(function () {
                id = $('#hide-id').val();
                var csrftoken = getCookie('csrftoken');
                $('.blog-title').each(function () {
                    $(this).click(function () {
                        $.ajax({
                            url: "{% url 'blog:add_click' %}",
                            type: 'POST',
                            data: {'id': id},
                            dataType: 'json',
                            beforeSend: function (xhr, settings) {
                                xhr.setRequestHeader("X-CSRFToken", csrftoken)
                            },
                            success: function (data) {
                                console.log('1324');
                            }
                        })
                    })
                })

            })
        </script>
    {% endblock %}
{% endblock %}

MyBlog/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}homepage{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/pagination.css' %}">
{% endblock %}

{% block body %}
    <div class="body">
        {% for topic in topics.object_list %}
            <div class="collects">
                <p>收藏数:</p>
                <p>{{ topic.collect }}</p>
            </div>
            <input id="article-id" type="hidden" class="" value="{{ topic.id }} ">
            <h4><a id="to-article" class="aa" href="{% url 'blog:article' topic.id %}">{{ topic.title }}</a></h4>
            <p><b>author:</b><a href="#">{{ topic.user.username }}</a></p>
            <p><b>发布时间:</b>{{ topic.time | date:"Y-m-d H:i" }}</p>
            <hr/>
        {% endfor %}
    </div>
    {% load i18n %}
    <div class="paginate">
        {% if topics.has_previous %}
            <a href="?{{ topics.previous_page_number.querystring }}"
               class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
        {% else %}
            <span class="disabled">&lsaquo;&lsaquo; {% trans "previous" %}</span>
        {% endif %}
        {% for page in topics.pages %}
            {% if page %}
                {% ifequal page topics.number %}
                    <span class="current page">{{ page }}</span>
                {% else %}
                    <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                {% endifequal %}
            {% else %}...{% endif %}
        {% endfor %}
        {% if topics.has_next %}
            <a href="?{{ topics.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
        {% else %}
            <span class="disabled">{% trans "next" %} &rsaquo;&rsaquo;</span>
        {% endif %}
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function click_article() {
            $('.aa').each(function () {
                $(this).click(function () {
                    var csrftoken = getCookie('csrftoken');
                    var val_art = $(this).parent().prev().val();
                    console.log(val_art);
                    $.ajax({
                        'url': '{% url 'click' %}',
                        'data': {'id': val_art},
                        'dataType': 'json',
                        'type': 'POST',
                        beforeSend: function (xhr, settings) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken)
                        },
                        success: function (ret) {
                            console.log('click add 1')
                        }

                    })
                })
            })
        }

        $(function () {
            click_article();
        });
    </script>
{% endblock %}